---
id: 230906 
created_date: 202309061422
type: note
---

# 230906

## NOTES

{@task} debug for runtime

Hi:

@Manik and I did a bit of debugging. 

Test:

  > call `orchestrator.run(evalAiResult.query, evalAiResult).get()` from Jupyter context. 

      >> result: stack trace pointing with the relevant log:

          Unable to load metadata file at path /genAiBase/resource/code/c3genai/dataset.py: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/local/share/c3/runtimes/8884993117660592827/py-query_orchestrator-server-py4j/lib/python3.9/site-packages/pandas/_libs/window/aggregations.cpython-39-x86_64-linux-gnu.so) (Unknown file#None)

      >> note: the stack trace was only generated when the `genAiBase` code was duplicated in the Jupyter pod (instead of calling the base type). Calling the base type resulted in an error (but did not provide a stack trace).

  > Install runtime `py-query_orchestrator-client-ipython` on the running Jupyter node. 

      >> result: call successful when reference (client) runtime was installed on local (client) pod.

  > Call Lambda runtime with `py-query_orchestrator-server-py4j` on the running Jupyter node.

      >> result: call successful when reference (server) runtime was instantiated in the Jupyter pod and call by way of Lambda.

Possible next steps:

  Review  possible changes to due to upgrade from `8.3.0-rc+1143` to `8.3.0-rc+962`.

Current action: 

  Investigate possibility/effectiveness of clearing / reinstalling runtime cache on the server node.

  File EXC ticket to review root cause attributable to these differences.

Stack Trace: 

```json

"engineLog" : "[\"Traceback (most recent call last):\\n  File \\\"/tmp/ipykernel_1900/3002736328.py\\\", line 688, in run\\n    ensureInitialized(this)\\n  File \\\"/tmp/ipykernel_1900/3002736328.py\\\", line 108, in ensureInitialized\\n    initialize(this)\\n  File \\\"/tmp/ipykernel_1900/3002736328.py\\\", line 76, in initialize\\n    tool.initialize(forceReload)\\n  File \\\"/c3/platform/src/remote/ServerConnection.py-client.py\\\", line 350, in initialize\\n  File \\\"/c3/platform/src/remote/ServerConnection.py-client.py\\\", line 342, in _exec_method_common\\n  File \\\"/c3/platform/src/remote/ServerConnection.py-client.py\\\", line 474, in _exec_remote_method\\n  File \\\"/c3/platform/src/remote/ServerConnection.py-client.py\\\", line 379, in _parse_response\\nRuntimeError: Error invoking Python method Genai.EvalMetricsQueryTool#initialize executing in runtime py-query_orchestrator on server using py4j: AttributeError: Error accessing attribute 'initialize' on instance of type 'Genai.EvalMetricsQueryTool':\\n<class 'RuntimeError'>: Unable to load metadata file at path /genAiBase/resource/code/c3genai/c3_eval_agent/tools/create_eval_metrics.py: Unable to load metadata file at path /genAiBase/resource/code/c3genai/c3_eval_agent/tools/choose_metrics.py: Unable to load metadata file at path /genAiBase/resource/code/c3genai/c3_eval_agent/tools/load_type_documentation_vectorstore.py: Unable to load metadata file at path /genAiBase/resource/code/c3genai/dataset.py: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/local/share/c3/runtimes/8884993117660592827/py-query_orchestrator-server-py4j/lib/python3.9/site-packages/pandas/_libs/window/aggregations.cpython-39-x86_64-linux-gnu.so) (Unknown file#None)\\n    File \\\"/platform/src/remote/ServerConnection.py\\\", line 1303, in valueGetattrFunc\\n\\n    File \\\"/platform/src/remote/ServerConnection.py-server.py\\\", line 851, in wrap_and_call\\n\\n    File \\\"/platform/src/remote/ServerConnection.py-server.py\\\", line 863, in wrapCallAndCatch\\n\\nError calling /api/8/Genai.EvalMetricsQueryTool/initialize with [{\\\"type\\\":\\\"Genai.EvalMetricsQueryTool\\\",\\\"meta\\\":{\\\"type\\\":\\\"Meta\\\",\\\"deserSource\\\":\\\"meta://genAiBase/metadata/Genai.EvalMetricsQueryTool/default.json\\\"},\\\"id\\\":\\\"EvalMetricsQueryTool_default\\\"},false]\\n\", \"Traceback (most recent call last):\\n  File \\\"/tmp/ipykernel_1900/3002736328.py\\\", line 688, in run\\n    ensureInitialized(this)\\n  File \\\"/tmp/ipykernel_1900/3002736328.py\\\", line 108, in ensureInitialized\\n    initialize(this)\\n  File \\\"/tmp/ipykernel_1900/3002736328.py\\\", line 76, in initialize\\n    tool.initialize(forceReload)\\n  File \\\"/c3/platform/src/remote/ServerConnection.py-client.py\\\", line 350, in initialize\\n  File \\\"/c3/platform/src/remote/ServerConnection.py-client.py\\\", line 342, in _exec_method_common\\n  File \\\"/c3/platform/src/remote/ServerConnection.py-client.py\\\", line 474, in _exec_remote_method\\n  File \\\"/c3/platform/src/remote/ServerConnection.py-client.py\\\", line 379, in _parse_response\\nRuntimeError: Error invoking Python method Genai.EvalMetricsQueryTool#initialize executing in runtime py-query_orchestrator on server using py4j: AttributeError: Error accessing attribute 'initialize' on instance of type 'Genai.EvalMetricsQueryTool':\\n<class 'RuntimeError'>: Unable to load metadata file at path /genAiBase/resource/code/c3genai/c3_eval_agent/tools/create_eval_metrics.py: Unable to load metadata file at path /genAiBase/resource/code/c3genai/c3_eval_agent/tools/choose_metrics.py: Unable to load metadata file at path /genAiBase/resource/code/c3genai/c3_eval_agent/tools/load_type_documentation_vectorstore.py: Unable to load metadata file at path /genAiBase/resource/code/c3genai/dataset.py: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/local/share/c3/runtimes/8884993117660592827/py-query_orchestrator-server-py4j/lib/python3.9/site-packages/pandas/_libs/window/aggregations.cpython-39-x86_64-linux-gnu.so) (Unknown file#None)\\n    File \\\"/platform/src/remote/ServerConnection.py\\\", line 1303, in valueGetattrFunc\\n\\n    File \\\"/platform/src/remote/ServerConnection.py-server.py\\\", line 851, in wrap_and_call\\n\\n    File \\\"/platform/src/remote/ServerConnection.py-server.py\\\", line 863, in wrapCallAndCatch\\n\\nError calling /api/8/Genai.EvalMetricsQueryTool/initialize with [{\\\"type\\\":\\\"Genai.EvalMetricsQueryTool\\\",\\\"meta\\\":{\\\"type\\\":\\\"Meta\\\",\\\"deserSource\\\":\\\"meta://genAiBase/metadata/Genai.EvalMetricsQueryTool/default.json\\\"},\\\"id\\\":\\\"EvalMetricsQueryTool_default\\\"},false]\\n\"]",

```

## LINKS

## TODO

- TODO: put on radar to implement iSpy API
